[project]
name = "parserologan"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[dependencies]
python = ">=3.12.8,<3.13"
pip = ">=23.2.1,<24"
numpy = ">=2.2.3,<3"
pandas = ">=2.2.3,<3"
biopython = ">=1.85,<2"
pyhmmer = ">=0.11.0,<0.12"
pyrodigal-gv = ">=0.3.2,<0.4"
textual = ">=1.0.0,<2"
rich-click = ">=1.8.5,<2"
seqkit = ">=2.9.0,<3"
awscli = ">=2.24.3,<3"
